title: Isabella Cheng
author: Isabella Cheng
email: Icheng@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  instagram : isbll_chng 
  github    : icheng31 

show_excerpts: true# set to false to remove excerpts on the homepage
theme: jekyll-theme-architect
