title: Welcome to Izzy's Blog
author: Isabella Cheng
email: Icheng@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my blog to talk about me and show off my achievements.

show_excerpts: true# set to false to remove excerpts on the homepage
theme: jekyll-theme-architect
